# frozen_string_literal: true

name              'postfix'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures postfix for client or outbound relayhost, or to do SASL auth'
version           '7.0.1'
source_url        'https://github.com/sous-chefs/postfix'
issues_url        'https://github.com/sous-chefs/postfix/issues'
chef_version      '>= 16.0'

supports 'amazon'
supports 'almalinux'
supports 'debian'
supports 'fedora'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'rocky'
supports 'ubuntu'
