name              'postfix'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures postfix for client or outbound relayhost, or to do SASL auth'
version           '6.0.4'
source_url        'https://github.com/sous-chefs/postfix'
issues_url        'https://github.com/sous-chefs/postfix/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'ubuntu'
