control 'sasl_auth_one' do
  describe file '/etc/postfix/sasl_passwd' do
    its('content') do
      should cmp <<~EOF
        # Auto-generated by Chef.
        # Local modifications will be overwritten.

        relayhost kitchenuser:not-a-real-thing
        smtp_sasl_passwd :
        smtp_sasl_user_name :
      EOF
    end
  end

  describe postfix_conf '/etc/postfix/main.cf' do
    its('smtp_sasl_password_maps') { should eq 'hash:/etc/postfix/sasl_passwd' }
  end
end
