control 'aliases-db' do
  # hash databases compile to .db, lmdb to .lmdb — pick whichever exists
  aliases_db = %w(/etc/aliases.db /etc/aliases.lmdb).find { |f| file(f).exist? } || '/etc/aliases.db'

  describe file aliases_db do
    it { should exist }
    its('mtime') { should be >= file('/etc/aliases').mtime }
  end
end

control 'aliases' do
  describe file '/etc/aliases' do
    its('content') do
      should cmp <<~EOF
        #
        # Auto-generated by Chef.
        # Local modifications will be overwritten.
        #
        # See man 5 aliases for format
        postmaster:    root

        foo1: bar
        "foo@bar": foo
        foo2: "|/usr/bin/bar"
        foo3: foo,bar
        foo4: foo@example.com
        foo5: foo,bar
      EOF
    end
  end
end
